CREATE TABLE DEPT03
AS
SELECT *
FROM DEPT;

DESC DEPT03;

SELECT *
FROM DEPT03;

ALTER TABLE DEPT03
MODIFY(DEPTNO NUMBER(4));

ALTER TABLE DEPT03
MODIFY(LOC VARCHAR2(20)); 

CREATE TABLE SAM01
AS
SELECT EMPNO, ENAME, JOB, SAL
FROM EMP
WHERE 1 = 0;

SELECT *
FROM SAM01;

INSERT INTO SAM01
VALUES(1000, 'APPLE', 'POLICE', 10000);

INSERT INTO SAM01
VALUES(1010, 'BANANA', 'NURSE', 15000);

INSERT INTO SAM01
VALUES(1020, 'ORANGE', 'DOCTOR', 25000);

INSERT INTO SAM01
(EMPNO, ENAME, SAL)
VALUES(1030, 'VAT', 2000);

SELECT *
FROM SAM01;

DROP TABLE SNACK;

CREATE TABLE SNACK
(
    PRODUCT_NO        NUMBER(4) PRIMARY KEY,
    SNACK_NAME        VARCHAR2(50),
    SNACK_PRICE        NUMBER(5, 1),
    PRODUCT_DATE     DATE
);

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER
(
    NAME            VARCHAR2(20),
    SOCIAL_NO      NUMBER(14) PRIMARY KEY,
    BUY_SNACK     NUMBER(4)
            REFERENCES SNACK(PRODUCT_NO)
);

SELECT *
FROM SNACK;

SELECT*
FROM CUSTOMER;

INSERT INTO SNACK
(PRODUCT_NO, SNACK_NAME, SNACK_PRICE, PRODUCT_DATE)
VALUES
(1000, '새우깡', 1000.0, SYSDATE);

INSERT INTO SNACK
(PRODUCT_NO, SNACK_NAME, SNACK_PRICE, PRODUCT_DATE)
VALUES
(1001, '맛동산', 2000.0, SYSDATE);

INSERT INTO SNACK
(PRODUCT_NO, SNACK_NAME, SNACK_PRICE, PRODUCT_DATE)
VALUES
(1002, '몽쉘', 3000.0, SYSDATE);

INSERT INTO CUSTOMER
( NAME, SOCIAL_NO, BUY_SNACK)
VALUES
('정이랑', 88, 1002);

INSERT INTO CUSTOMER
( NAME, SOCIAL_NO, BUY_SNACK)
VALUES
('정준석', 97, 1001);

INSERT INTO CUSTOMER
( NAME, SOCIAL_NO, BUY_SNACK)
VALUES
('정혜미', 84, 1000);

INSERT INTO CUSTOMER
( NAME, SOCIAL_NO, BUY_SNACK)
VALUES
('정연수', 56, 1000);

SELECT *
FROM SNACK;

SELECT *
FROM CUSTOMER;

SELECT*
FROM USER_CONSTRAINTS;   -- 제약조건을 볼수있다

