
select * 
from dept;

--유일하면서도 NULL이 아닌 값 만 저장될 수 있는 컬럼?
--기본키

SELECT *
FROM USER_CONSTRAINTS;

-- 기존의 것을 드랍하지안고 수정을 통해 제약조건을 주자

--[형식]
--ALTER TABLE 테이블명
--ADD CONSTRAINT 제약조건명 제약조건(지정할 컬럼명);
ALTER TABLE DEPT
ADD CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO);
--제약조건은 DESC로 나오지않고 따로 관리된다 -데이터 사전
--테이블을 만들때 제약조건도 만들수 있지만, 테이블을 만들고 ALTER TABLE 제약조건을 따로 만드는게 더 좋다(유지,보수 편리)


--제약조건은 수정은 불가능
--제약조건을 지우고 다시 만든다
--CONSTRAINT NAME은 유일하다, 똑같은 이름은 존재하지 않는다 BUT 어떤 컬럼이 지워졌는지는 모름
ALTER TABLE DEPT
DROP CONSTRAINT DEPT_DEPTNO_PK;


--EMP와 DEPT는 관계를 가짐(부서안에 사원이 있는 것이므로)


SELECT *
FROM EMP06;

CREATE TABLE EMP06
AS
SELECT *
FROM EMP;

INSERT INTO EMP06
(EMPNO, ENAME, DEPTNO)
VALUES
(8000, '홍길동', 50);   --50번 부서명을 찾으러 DEPT를 갔는데 50번 부서는 존재하지 않음 -누군가 잘못입력한 것 이것을 막으려면?

SELECT *
FROM DEPT;

SELECT *
FROM EMP06;

ROLLBACK;     --홍길동 자료 넣은 것 다시삭제,  

DROP TABLE DEPT02;

CREATE TABLE DEPT02
(
    DEPTNO  NUMBER(2) PRIMARY KEY,
    DNAME   VARCHAR2(14),
    LOC       VARCHAR2(13)
);

DESC EMP;

CREATE TABLE EMP07
(
    EMPNO        NUMBER(4) PRIMARY KEY,   
    ENAME        VARCHAR2(10), 
    JOB           VARCHAR2(9),  
    MGR           NUMBER(4),    
    HIREDATE     DATE,         
    SAL            NUMBER(7,2),  
    COMM         NUMBER(7,2),  
    DEPTNO       NUMBER(2) 
            CONSTRAINT EMP07_DEPTNO_DEPT02_FK REFERENCES DEPT02(DEPTNO)  
);

SELECT *
FROM EMP06;

SELECT *
FROM EMP07;

SELECT *
FROM DEPT02;

INSERT INTO EMP07
(EMPNO, ENAME, DEPTNO)
VALUES
(8000, '홍길동', 50);   --입력안되도록 막고있음, 50이란 부서는 존재하지 않으므로

INSERT INTO EMP07
(EMPNO, ENAME, DEPTNO)
VALUES
(8000, '홍길동', 10);

INSERT INTO EMP07
(EMPNO, ENAME, DEPTNO)
VALUES
(7499, 'ALLEN', 30);

INSERT INTO EMP07
(EMPNO, ENAME, DEPTNO)
VALUES
(7369, 'SMITH', 20);

SELECT *
FROM DEPT02;

INSERT INTO DEPT02
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT02
VALUES(20, 'RESEARCH', 'DALLAS');

INSERT INTO DEPT02
VALUES(30, 'SALES', 'CHICAGO');

INSERT INTO DEPT02
VALUES(40, 'OPERATIONS', 'BOSTON');


--DEFAULT 제약조건

CREATE TABLE DEPT03(
    DEPTNO NUMBER(2) PRIMARY KEY   --기본키는 유일성, 여기다 DEFAULT 못씀
    , DNAME VARCHAR2(14)
    , LOC VARCHAR2(13) DEFAULT 'SEOUL'  --LOC에 대한 값을 직접 넣지 않는다면 무조건 SEOUL을 넣겠다는 것
);                                                       --DEFAULT는 CONSTRAINT 를 앞에 붙이지 않는다   

INSERT INTO DEPT03
(DEPTNO, DNAME)
VALUES(20, 'ACCOUNTING');

INSERT INTO DEPT03
(DEPTNO, DNAME, LOC)
VALUES(30, 'ACCOUNTING', 'JINJU');


INSERT INTO DEPT03
VALUES(40, 'COL ALL INPUT', NULL);

SELECT *
FROM DEPT03;

INSERT INTO DEPT02
(DEPTNO, DNAME)
VALUES(60, 'ACCOUNTING');

INSERT INTO DEPT02
(DEPTNO, DNAME, LOC)
VALUES(70, 'ACCOUNTING', 'JINJU');

SELECT *
FROM DEPT02;

--제약조건을 수정하기 (안된다고 생각하라)- 제약조건은 지우고 다시 만드는 것

SELECT *
FROM EMP06;

SELECT *
FROM USER_CONSTRAINTS;

ALTER TABLE EMP06
MODIFY EMPNO CONSTRAINT EMP06_EMPNO_NN NOT NULL;

ALTER TABLE EMP06
DROP CONSTRAINT SYS_C007034;



DROP TABLE DEPT03;


CREATE TABLE EMP_BACKUP
AS SELECT *
FROM EMP;

CREATE TABLE DEPT_BACKUP
AS SELECT *
FROM DEPT;


-- EMP 와 DEPT 를 살펴 제약조건들을 추가하라

SELECT *
FROM USER_CONSTRAINTS;


SELECT *
FROM DEPT;

SELECT *
FROM EMP;


ALTER TABLE DEPT
MODIFY (DNAME CONSTRAINT DEPT_DNAME_NN NOT NULL);  --이미 존재하는 컬럼이므로 컬럼자체를 수정하면서 - 

ALTER TABLE DEPT
MODIFY (LOC CONSTRAINT DEPT_LOC_NN NOT NULL);

DESC EMP;

ALTER TABLE EMP                                                        --기존 컬럼에 제약조건만 추가할때
ADD CONSTRAINT EMP_EMPNO_PK PRIMARY KEY(EMPNO);

ALTER TABLE EMP
DROP CONSTRAINT EMP_EMPNO_PK;

ALTER TABLE EMP                            
MODIFY (ENAME NOT NULL);


ALTER TABLE EMP                            
MODIFY (JOB NOT NULL);


ALTER TABLE EMP                            
MODIFY (HIREDATE NOT NULL);

ALTER TABLE EMP                            
MODIFY (SAL NOT NULL);

ALTER TABLE EMP                                                  
ADD CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES DEPT(DEPTNO);